/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umass.cs.indri;


public class IndexStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IndexStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      indriJNI.delete_IndexStatus(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(IndexStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void status(int code, String documentPath, String error, int documentsIndexed, int documentsSeen) {
    indriJNI.IndexStatus_status(swigCPtr, code, documentPath, error, documentsIndexed, documentsSeen);
  }

  public IndexStatus() {
    this(indriJNI.new_IndexStatus(), true);
    indriJNI.IndexStatus_director_connect(this, swigCPtr);
  }

  // enums and constants
  public final static int FileOpen = indriJNI.get_IndexStatus_FileOpen();
  public final static int FileSkip = indriJNI.get_IndexStatus_FileSkip();
  public final static int FileError = indriJNI.get_IndexStatus_FileError();
  public final static int FileClose = indriJNI.get_IndexStatus_FileClose();
  public final static int DocumentCount = indriJNI.get_IndexStatus_DocumentCount();
}
