
all: 
	$(MAKE) -C antlr/obj -f ../src/Makefile
	$(MAKE) -C xpdf/obj -f ../src/Makefile
	$(MAKE) -C lemur/obj -f ../src/Makefile

clean:
	$(MAKE) clean -C antlr/obj -f ../src/Makefile
	$(MAKE) clean -C xpdf/obj -f ../src/Makefile
	$(MAKE) clean -C lemur/obj -f ../src/Makefile

install: 
	$(MAKE) install -C antlr/obj -f ../src/Makefile
	$(MAKE) install -C xpdf/obj -f ../src/Makefile
	$(MAKE) install -C lemur/obj -f ../src/Makefile

stamp:


