SHELL = /bin/sh


auto:
	/usr/dan/users9/dfisher/ciir/doxygen-1.4.2/bin/doxygen config

manual: auto
	cp /afs/cs/project/lemur/www/doxygen-index.html html/index.html


clean:
	rm -rf html latex rtf man